services:
  - type: web
    name: harmony-hands-erp
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: harmony-hands-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"

databases:
  - name: harmony-hands-db
    databaseName: harmony_hands
    user: harmony_user